name: Publish

on:
  release:
    types: [ created ]

jobs:
  tool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
      - name: Set Version
        run: echo ${{ github.ref_name }} | sed -r "s/^v/GDTOOL_VERSION=/" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore ./GeometryDash.Console.sln
      - name: Release build
        run: dotnet build -c Release ./GeometryDash.Console/GeometryDash.Console.csproj
      - name: Pack
        run: dotnet pack -c Release -o ./pack/ /p:PackageVersion=$GDTOOL_VERSION ./GeometryDash.Console/GeometryDash.Console.csproj
      - name: Push to NuGet
        run: dotnet nuget push ./pack/GeometryDash.Console*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
  independent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        runtime: [ linux-x64, win-x64 ]
        project: [ DatPack ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Set Version
        run: echo ${{ github.ref_name }} | sed -r "s/^v/GDTOOL_VERSION=/" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore ./GeometryDash.Console.sln
      - name: publish
        run: dotnet publish ./${{ matrix.project }}/${{ matrix.project }}.csproj -r ${{ matrix.runtime }} -p:PublishSingleFile=true --self-contained true
      - name: edit binaries
        run: |
          cd ./${{ matrix.project }}/bin/Release/net8.0/${{ matrix.runtime }}/publish
          rm *.pdb
          for file in *; do
             if [[ $file == *.* ]]; then
               base="${file%.*}"
               ext="${file##*.}"
               mv "$file" "${base}-${{ matrix.runtime }}.${ext}"
             else
               mv "$file" "${file}-${{ matrix.runtime }}"
             fi
           done
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./${{ matrix.project }}/bin/Release/net8.0/${{ matrix.runtime }}/publish/*
